spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root123@
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 86400
    refreshTokenExpiration: 604800
stripe:
  secretKey : ${STRIPE_SECRET_KEY}

webSiteUrl : http://localhost:4242